name: Buf checks

on: 
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'rest/*'
      - 'name-resolution/*'
      - 'meson.build'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'rest/*'
      - 'name-resolution/*'
      - 'meson.build'

jobs:
  lint-protos-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'stable'
  lint-protos-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'staging'
  breaking-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.5.0
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/harmony-development/protocol.git#branch=main"
