name: Buf checks

on: [push, pull_request]

jobs:
  validate-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.3.1
      - uses: bufbuild/buf-lint-action@v0.3.0
      - uses: bufbuild/buf-breaking-action@v0.4.0
        with:
          against: "https://github.com/harmony-development/protocol#branch=main"
